# Generated by Django 5.0.4 on 2024-05-04 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_adopted', models.BooleanField(default=False)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('horse', 'Horse'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('snake', 'Snake'), ('turtle', 'Turtle'), ('fish', 'Fish'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('behavior', models.CharField(blank=True, choices=[('tamed', 'Tamed'), ('wild', 'Wild'), ('friendly', 'Friendly'), ('aggressive', 'Aggressive'), ('calm', 'Calm')], max_length=20, null=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='pet_photos/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('vaccinated', models.BooleanField(default=False)),
                ('dewormed', models.BooleanField(default=False)),
                ('neutered_spayed', models.BooleanField(default=False)),
                ('microchipped', models.BooleanField(default=False)),
                ('friendly_with_kids', models.BooleanField(default=False)),
                ('friendly_with_dogs', models.BooleanField(default=False)),
                ('friendly_with_cats', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('adoption_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('coat_length', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('injured', 'Injured'), ('sick', 'Sick'), ('special_needs', 'Special Needs')], default='healthy', max_length=20)),
                ('adopted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopter', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
